config/routes.rb
Rails.application.routes.draw do
  root to: 'application#index'
  get '/auth/:provider/callback', to: 'application#spotify_auth_callback'
  get '/logout', to: 'application#logout'
  namespace :api do
    get '/current', to: 'api#current'
    get '/lyrics', to: 'api#lyrics'
    get '/tabs', to: 'api#tabs'
    post '/current', to: 'api#control'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spotify.rb
require 'net/http'
require "base64"
module Spotify
  class Session
    def initialize user_id
      @user = User.find_by(id: user_id)
      # if !expired?
      #   @auth_hash["credentials"]["token"] = refresh_access_token
      # end
    end
    def expired?
      return true if @user.nil?
      @user.token_expires_at < Time.now.to_i
    end
    def basic
      {
        name: @user.name,
        email: @user.email,
        image: @user.image
      }
    end
    def get_current user
        current = JSON.parse(HTTParty.get('https://api.spotify.com/v1/me/player?market=US', headers: {
          Authorization: "Bearer #{user.access_token}"
        }).body || '{}')
        if current["error"]
          refresh_access_token(user)
          return {}
        end
        return {} if current.empty?
        {
          artist_name: current["item"]["artists"].map{|art| art["name"]}.join(", "),
          song_title: current["item"]["name"],
          duration_ms: current["item"]["duration_ms"],
          progress_ms: current["progress_ms"],
          image: current["item"]["album"]["images"][1]["url"],
          shuffle_state: current["shuffle_state"],
          repeat_state: current["repeat_state"],
          is_playing: current["is_playing"],
          # debug: current 
        }
    end

    def pause
      HTTParty.put('https://api.spotify.com/v1/me/player/pause', headers: {
        Authorization: "Bearer #{@user.access_token}"
      }).body
    end

    def play
      HTTParty.put('https://api.spotify.com/v1/me/player/play', headers: {
        Authorization: "Bearer #{@user.access_token}"
      }).body
    end

    def refresh_access_token(user)
      Rails.logger.debug "Refreshing Access Token"
      auth = Base64.strict_encode64("#{Rails.application.credentials.spotify_client_id}:#{Rails.application.credentials.spotify_client_secret}")
      response = JSON.parse(HTTParty.post("https://accounts.spotify.com/api/token", 
        headers: {
          Authorization: "Basic #{auth}"
        },
        body: {
          grant_type: 'refresh_token',
          refresh_token: user.refresh_token
        }
      ).body)
      Rails.logger.debug "Got #{response}"
      user.update(access_token: response["access_token"])
      response["access_token"]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/api/api_controller.rb
module URI
  def self.encode(a,b)
    a
  end
end

module Api

  class ApiController < ApplicationController
    skip_forgery_protection

    def current
      @spotify = Spotify::Session.new(session[:current_user_id])
      cur = @spotify.get_current(current_user)
      render json: cur
    end
    def control
      @spotify = Spotify::Session.new(session[:current_user_id])
      params["is_playing"] == "false" ? @spotify.play : @spotify.pause
      head 200
    end
    def lyrics
      Genius.access_token = Rails.application.credentials.genius_api_token
      results = Genius::Song.search(params[:query]).map do |result|
        {
          id: result.id,
          full_title: result.resource["full_title"]
        }
      end
      render json: results
    end
    def tabs
      res = HTTParty.get("https://www.ultimate-guitar.com/search.php?search_type=title&value=#{params[:q]}")
      actual_url = res.body.match(/https:\/\/tabs.ultimate-guitar.com\/tab\/([^&]+)/)[0]
      render json: {url: actual_url}
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  def index
    if session[:current_user_id]
      @spotify = Spotify::Session.new(session[:current_user_id])
    end
  end

  def spotify_auth_callback
    auth = request.env['omniauth.auth']
    email = auth["info"]["email"]
    @user = if User.exists? email: email
      User.find_by_email(email)
    else
      User.create!(
        name: auth["info"]["name"],
        email: email,
        image: auth["info"]["image"],
        access_token: auth['credentials']['token'],
        refresh_token: auth['credentials']['refresh_token'],
        token_expires_at: auth['credentials']['expires_at'],
      )
    end
    session[:current_user_id] = @user.id
    redirect_to root_path
  end

  def logout
    session.clear
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    return nil unless session[:current_user_id]
    User.find(session[:current_user_id])
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jamsesh</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;500&display=swap" rel="stylesheet"> 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div>
        <h1><a href='/'>Jam Sesh</a></h1>
        <small>A Spotify & Genius mashup</small>
      </div>
      <div style='text-align: right;'>
      <% if current_user %>
        <small><%= link_to "Log Out", logout_path %></small>
      <% else %>
        <%= form_tag "/auth/spotify", method: :post do %>
          <%= submit_tag "Log In with Spotify" %>
        <% end %>
      <% end %>
      </div>
    </header>
    <%= yield %>
    <% if current_user %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    
    <%= javascript_pack_tag 'application' %>
    <% end %>
  </body>
</html>